apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-cluster
spec:
  replicas: 3
  selector:
    matchLabels:
      app: maven-app
  template:
    metadata:
      labels:
        app: maven-app
    spec:
      containers:
        - name: maven-app
          image: ${IMAGE_TAG}
          ports:
            - containerPort: 8000
